oneYou2/api/urls.py
from django.conf.urls import url

from . import views
from release import views as release_views

app_name = 'react_api'
urlpatterns = [
    url(r'^preview/sites/(?P<site_identifier>[\w\-]+)/pages/(?P<page_slug_path>[\w|\W]+)/revisions/(?P<page_revision>[\w\-]+)/$',
        views.page_preview,
        name='page-preview'),

    url(r'^sites/(?P<site_identifier>[\w\-]+)/$',
        views.site_view,
        name='current-release-view'),

    url(r'^sites/(?P<site_identifier>[\w\-]+)/(?P<release_uuid>[\w\-]+)/$',
        views.release_view,
        name='specific-release-view'),

    url(r'^sites/(?P<site_identifier>[\w\-]+)/(?P<release_uuid>[\w\-]+)/pages/(?P<page_slug_path>[\w|\W]+)/$',
        views.page_detail,
        name='page-detail-by-slug'),
    url(r'^open-releases/$', release_views.open_releases, name='open-release-list')
]

oneYou2/images/models.py
import operator
from functools import reduce

from django.db import models
from django.db.models import Q
from django.db.models.signals import post_delete
from django.dispatch import receiver

from wagtail.core.models import PageRevision
from wagtail.images.models import Image, AbstractImage, AbstractRendition

from images.renditions import ONEYOU_RENDITIONS


class PHEImage(AbstractImage):
    # def get_usage(self):
    #     search_strings = ['"type": "image", "value": ' + str(self.id),
    #                       'image": ' + str(self.id),
    #                       'image\\": ' + str(self.id)]
    #     query = reduce(operator.or_, (Q(content_json__contains=string) for string in search_strings))
    #     page_ids = PageRevision.objects.filter(query).values('page_id')
    #     pages = OneYou2Page.objects.filter(id__in=page_ids).order_by('id')
    #     return pages

    admin_form_fields = Image.admin_form_fields + ()

    @property
    def link(self):
        if self.file:
            return self.file.url
        else:
            return ''

    def generate_or_get_all_renditions(self):
        if self.file:
            renditions_dict = {
                'original': self.file.url
            }
            for rendition in ONEYOU_RENDITIONS:
                for device, size in rendition[3].items():
                    renditions_dict[
                        '{}/{}/{}/{}'.format(rendition[0],
                                             rendition[1],
                                             rendition[2],
                                             device)
                    ] = self.get_rendition('fill-{}'.format(size)).url
                    # renditions_dict[size] = self.get_rendition('fill-{}'.format(size)).url
            return renditions_dict
        else:
            return {}
    
    def generate_and_get_rendition(self, rendition_size):
        if not self.file or rendition_size == 'none':
            return self.file.url
        else:
            return self.get_rendition('fill-{}'.format(rendition_size)).url

    def save(self, *args, **kwargs):
        super(PHEImage, self).save(*args, **kwargs)


class PHERendition(AbstractRendition):
    image = models.ForeignKey(
        PHEImage,
        related_name='renditions',
        on_delete=models.CASCADE,
    )

    class Meta:
        unique_together = (
            ('image', 'filter_spec', 'focal_point_key'),
        )


# Delete the source image file when an image is deleted
@receiver(post_delete, sender=PHEImage)
def image_delete(sender, instance, **kwargs):
    instance.file.delete(False)


# Delete the rendition image file when a rendition is deleted
@receiver(post_delete, sender=PHERendition)
def rendition_delete(sender, instance, **kwargs):
    instance.file.delete(False)

oneYou2/oneyou/models.py
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, TabbedInterface, ObjectList
from wagtail.core.fields import StreamField, RichTextField
from wagtail.core.models import Page
from wagtail.images.edit_handlers import ImageChooserPanel

from images.renditions import MOBILE_RENDITION_CHOICES, DESKTOP_RENDITION_CHOICES

from dctcmsbase.models import GeneralShelvePage, Tracking, Social
from dctcmsbase.panels import VIDEO_HOSTS
from dctcmsbase.shelves import (PageHeadingShelf, DividerShelf, InlineScriptShelf, BannerShelf,
    StandardGridShelf, IFrameShelf, InlineSvgShelf, SimplePageHeadingShelf, FindOutMoreDropDownShelf,
    CarouselShelf, TableShelf)
from wagtail.snippets.edit_handlers import SnippetChooserPanel

from home.models import SiteSettings

from .sharedcontent import Action
from .shelves import (OneYouGridShelf, OneYouTwoColumnShelf, OneYouSectionHeadingShelf, ActionPlanShelf,
    ActionPlanDisplayShelf, ArticleOneYouGridShelf)


class OneYouPage(GeneralShelvePage, Tracking, Social):
    body = StreamField([
        ('page_heading_shelf', PageHeadingShelf(icon='title')),
        ('section_heading_shelf', OneYouSectionHeadingShelf(classname='full title', icon='title')),
        ('divider_shelf', DividerShelf(label='Divider', icon='horizontalrule')),
        ('script_shelf', InlineScriptShelf(label='Script shelf', icon='code')),
        ('banner_shelf', BannerShelf(icon='title')),
        ('grid_shelf', OneYouGridShelf(icon='form')),
        ('two_column_shelf', OneYouTwoColumnShelf(label='Two Column Shelf', icon='grip')),
        ('iframe_shelf', IFrameShelf(label='IFrame', icon='placeholder')),
        ('svg_shelf', InlineSvgShelf(label='SVG shelf', icon='snippet')),
        ('simple_page_heading_shelf', SimplePageHeadingShelf(icon='title')),
        ('find_out_more_dropdown_shelf', FindOutMoreDropDownShelf(label='Link dropdown', icon='order-down')),
        ('carousel_shelf', CarouselShelf(icon='repeat')),
        ('action_plan_shelf', ActionPlanShelf(label='Action Plan Builder shelf', icon='form')),
        ('action_plan_display_shelf', ActionPlanDisplayShelf(label='Action Plan Display shelf', icon='form')),
        ('table_shelf', TableShelf(label='Table', icon='list-ul')),
    ], null=True, blank=True)

    @classmethod
    def allowed_subpage_models(cls):
        """
        Returns the list of page types that this page type can have as subpages,
        as a list of model classes
        """
        return [
            OneYouPage, RecipePage, ArticleOneYouPage,
        ]

    def serve_preview(self, request, mode_name, revision_id='latest'):
        site_name = SiteSettings.objects.get(site=self.get_site()).uid
        return super(OneYouPage, self).serve_preview(request, mode_name, site_name, revision_id)


OneYouPage._meta.get_field('og_title').default = 'One You - Home'
OneYouPage._meta.get_field('og_description').default = ('Start the fight back to a healthier you! One You is'
                                                         ' packed with practical tips, tools and free apps'
                                                         ' to help you improve your health today')
OneYouPage._meta.get_field('twitter_site').default = '@OneYouPHE'
OneYouPage._meta.get_field('twitter_title').default = 'One You - Home'
OneYouPage._meta.get_field('twitter_description').default = ('Start the fight back to a healthier you! One You is packed with'
                                                        ' practical tips, tools and free apps to help you improve'
                                                        ' your health today')


class RecipePage(GeneralShelvePage, Tracking, Social):
    DIFFICULTY_OPTIONS = (
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    )
    header_image = models.ForeignKey(
        'images.PHEImage',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    header_image_mobile_rendition = models.CharField(choices=MOBILE_RENDITION_CHOICES,
                                      verbose_name='Mobile Rendition',
                                      default='none',
                                      max_length=10)
    header_image_desktop_rendition = models.CharField(choices=DESKTOP_RENDITION_CHOICES,
                                      verbose_name='Desktop Rendition',
                                      default='none',
                                      max_length=10)
    recipe_name = models.CharField(max_length=255, null=True, blank=True)
    tags = models.CharField(max_length=255, null=True, blank=True)
    serves = models.IntegerField(default=0)
    preparation_time = models.IntegerField(default=0)
    difficulty = models.CharField(max_length=255, choices=DIFFICULTY_OPTIONS, default='medium')
    ingredients_list = RichTextField(null=True, blank=True)
    instructions = RichTextField(null=True, blank=True)

    header_gradient = models.BooleanField(default=False)
    video_id = models.CharField(null=True, blank=True, max_length=50)
    host = models.CharField(choices=VIDEO_HOSTS, max_length=15, default='brightcove', null=True, blank=True)

    content_panels = [
        MultiFieldPanel(
            [
                FieldPanel('title'),
                FieldPanel('tags'),
            ],
            heading='General',
        ),
        MultiFieldPanel(
            [
                ImageChooserPanel('header_image'),
                FieldPanel('header_image_mobile_rendition'),
                FieldPanel('header_image_desktop_rendition'),
                FieldPanel('header_gradient'),
                FieldPanel('recipe_name'),
                FieldPanel('video_id'),
                FieldPanel('host'),
            ],
            heading='Header',
        ),
        MultiFieldPanel(
            [
                FieldPanel('serves'),
                FieldPanel('preparation_time'),
                FieldPanel('difficulty'),
                FieldPanel('ingredients_list'),
                FieldPanel('instructions'),
            ],
            heading='Recipe details',
        ),
        FieldPanel('release'),
        SnippetChooserPanel('page_theme'),
    ]

    edit_handler = TabbedInterface([
        ObjectList(content_panels, heading='Content'),
        ObjectList(GeneralShelvePage.info_content_panels, heading='Notes'),
        ObjectList(GeneralShelvePage.meta_content_panels, heading='Meta'),
        ObjectList(Page.promote_panels, heading='Settings'),
    ])

    @classmethod
    def allowed_subpage_models(cls):
        """
        Returns the list of page types that this page type can have as subpages,
        as a list of model classes
        """
        return [
            OneYouPage, RecipePage, ArticleOneYouPage,
        ]


class ArticleOneYouPage(GeneralShelvePage, Tracking, Social):
    body = StreamField([
        ('page_heading_shelf', PageHeadingShelf(icon='title')),
        ('banner_shelf', BannerShelf(icon='title')),
        ('section_heading_shelf', OneYouSectionHeadingShelf(classname='full title', icon='title')),
        ('svg_shelf', InlineSvgShelf(label='SVG shelf', icon='snippet')),
        ('grid_shelf', ArticleOneYouGridShelf(icon='form')),
    ], null=True, blank=True)

    @classmethod
    def allowed_subpage_models(cls):
        """
        Returns the list of page types that this page type can have as subpages,
        as a list of model classes
        """
        return [
            OneYouPage, RecipePage, ArticleOneYouPage,
        ]

    def serve_preview(self, request, mode_name, revision_id='latest'):
        site_name = SiteSettings.objects.get(site=self.get_site()).uid
        return super(ArticleOneYouPage, self).serve_preview(request, mode_name, site_name, revision_id)


ArticleOneYouPage._meta.get_field('og_title').default = 'One You - Home'
ArticleOneYouPage._meta.get_field('og_description').default = ('Start the fight back to a healthier you! One You is'
                                                         ' packed with practical tips, tools and free apps'
                                                         ' to help you improve your health today')
ArticleOneYouPage._meta.get_field('twitter_site').default = '@OneYouPHE'
ArticleOneYouPage._meta.get_field('twitter_title').default = 'One You - Home'
ArticleOneYouPage._meta.get_field('twitter_description').default = ('Start the fight back to a healthier you! One You is packed with'
                                                        ' practical tips, tools and free apps to help you improve'
                                                        ' your health today')

# Add OneYouPage from page creation
Page.subpage_types.append(OneYouPage)
# Page.subpage_types.append(RecipePage)
# Page.subpage_types.append(ArticleOneYouPage)

oneYou2/images/templates/wagtailimages/images/edit.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailimages_tags wagtailadmin_tags staticfiles i18n l10n %}
{% block titletag %}{% blocktrans with title=image.title %}Editing image {{ title }}{% endblocktrans %}{% endblock %}
{% block extra_css %}
    {{ block.super }}

    <!-- Focal point chooser -->
    <link rel="stylesheet" href="{% static 'wagtailimages/css/vendor/jquery.Jcrop.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'wagtailimages/css/focal-point-chooser.css' %}" type="text/css">
{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>

    <!-- Focal point chooser -->
    <script src="{% static 'wagtailadmin/js/vendor/jquery.ba-throttle-debounce.min.js' %}"></script>
    <script src="{% static 'wagtailimages/js/vendor/jquery.Jcrop.min.js' %}"></script>
    <script src="{% static 'wagtailimages/js/focal-point-chooser.js' %}"></script>
{% endblock %}

{% block content %}
    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=image.title icon="image" %}

    <form action="{% url 'wagtailimages:edit' image.id %}" method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="row row-flush nice-padding">

            <div class="col5">
                <ul class="fields">
                    {% for field in form %}

                        {% if field.name == 'file' %}
                            {% include "wagtailimages/images/_file_field_as_li.html" %}
                        {% elif field.is_hidden %}
                            {{ field }}
                        {% else %}
                            {% include "wagtailadmin/shared/field_as_li.html" %}
                        {% endif %}

                    {% endfor %}
                </ul>
            </div>

            <div class="col5 divider-after">
                <h2 class="label">{% trans "Focal point (optional)" %}</h2>
                <p>{% trans "To define this image's most important region, drag a box over the image below." %} {% if image.focal_point %}({% trans "Current focal point shown" %}){% endif %}</p>

                {% image image max-800x600 as rendition %}

                <div class="focal-point-chooser"
                    style="max-width: {{ rendition.width }}px; max-height: {{ rendition.height }}px;"
                    data-focal-point-x="{{ image.focal_point_x }}"
                    data-focal-point-y="{{ image.focal_point_y }}"
                    data-focal-point-width="{{ image.focal_point_width }}"
                    data-focal-point-height="{{ image.focal_point_height }}">

                    <img {{ rendition.attrs }} data-original-width="{{ image.width|unlocalize }}" data-original-height="{{ image.height|unlocalize }}" class="show-transparency">

                    <div class="current-focal-point-indicator{% if not image.has_focal_point %} hidden{% endif %}"></div>

                </div>
                <br />
                <button class="button button-secondary no remove-focal-point" type="button">{% trans "Remove focal area" %}</button>
            </div>

            <div class="col2 ">
                {% if url_generator_enabled %}
                    <a href="{% url 'wagtailimages:url_generator' image.id %}" class="button bicolor icon icon-link">{% trans "URL Generator" %}</a>
                    <hr />
                {% endif %}

                {% image image original as original_image %}

                <dl>
                    <dt>{% trans "Max dimensions" %}</dt>
                    <dd>{{ original_image.width }}x{{ original_image.height }}</dd>
                    <dt>{% trans "Filesize" %}</dt>
                    <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>

                    {% usage_count_enabled as uc_enabled %}
                    {% if uc_enabled %}
                        <dt><a href="{{ image.usage_url }}">{% trans "Usage" %}</a></dt>
                    {% endif %}
                </dl>
            </div>
        </div>

        <div class="row row-flush nice-padding">
            <div class="col5">
                <input type="submit" value="{% trans 'Save' %}" class="button" />
                {% if user_can_delete %}
                    <a href="{% url 'wagtailimages:delete' image.id %}" class="button button-secondary no">{% trans "Delete image" %}</a>
                {% endif %}
            </div>
        </div>

    </form>
{% endblock %}